Build example program positions.c in Linux.

diff --git a/demo/c/build b/demo/c/build
--- a/demo/c/build
+++ b/demo/c/build
@@ -1,2 +1,9 @@
 #!/bin/bash
-gcc -Wall -Werror -o moonphase -I../../source/c ../../source/c/astronomy.c moonphase.c -lm
+Fail()
+{
+    echo "FATAL($0): $1"
+    exit 1
+}
+
+gcc -Wall -Werror -o moonphase -I../../source/c ../../source/c/astronomy.c moonphase.c -lm || Fail "Error building moonphase.c"
+gcc -Wall -Werror -o positions -I../../source/c ../../source/c/astronomy.c astro_demo_common.c positions.c -lm || Fail "Error building positions.c"
