worldmap.cpp demo now finds zenith locations.
The demo worldmap.cpp now also prints out the
geographic locations where the Sun/Moon appear
to be straight up (at the zenith) for the given time.
This illustrates that Astronomy_VectorObserver can
turn a geocentric vector into a location on the
Earth that is in the same direction from the Earth's
center that a given celestial body lies.

diff --git a/demo/c/run_worldmap b/demo/c/run_worldmap
--- a/demo/c/run_worldmap
+++ b/demo/c/run_worldmap
@@ -15,8 +15,13 @@ g++ -Wall -Werror -x c++ -std=c++11 -o worldmap $BUILDOPT \
 
 echo "run_worldmap: creating image"
 
-rm -f sun_moon_map.png
-time ./worldmap sun_moon_map.png 2022-04-09T16:05:35Z || exit $?
+rm -f sun_moon_map.png test/worldmap.txt
+time ./worldmap sun_moon_map.png 2022-04-09T16:05:35Z > test/worldmap.txt || exit $?
+more test/worldmap.txt || exit $?
+if ! diff test/worldmap{,_correct}.txt; then
+    echo "run_worldmap: FAIL - incorrect zenith location output."
+    exit 1
+fi
 ls -l sun_moon_map.png || exit $?
 sha256sum -c worldmap.sha256 || exit $?
 
