Dump unit test failures to GitHub Actions log.
If the Kotlin unit tests fail on my home system,
I can easily read them. But if they fail on GitHub Actions,
I would have no idea what went wrong. So now I dump
the XML output of the unit tests if the gradlew command
fails for any reason. Then I can see the problem in
the GitHub Actions console log.

diff --git a/generate/unit_test_kotlin b/generate/unit_test_kotlin
--- a/generate/unit_test_kotlin
+++ b/generate/unit_test_kotlin
@@ -9,7 +9,12 @@ Fail()
 
 cd ../source/kotlin || Fail "Cannot change dir to ../source/kotlin"
 rm -rf build
-./gradlew assemble build test dokkaGfm || Fail "Error building/testing Kotlin code."
+if ! ./gradlew assemble build test dokkaGfm; then
+    # Dump the contents of the unit tests to the console,
+    # so if the test fails on GitHub Actions, I can see what went wrong.
+    cat build/test-results/test/*.xml
+    Fail "Error building/testing Kotlin code."
+fi
 
 # The above gradlew call also generated all the Markdown documentation.
 # The other languages do this from makedoc, but Kotlin is an exception.
