Simplified `demotest` scripts for C, C#, JS, PY.
I made the scripts for testing the demos for
C, C#, JavaScript, and Python follow the improved
pattern used for Java and Kotlin: much smaller
and easier to maintain thanks to bash functions.

diff --git a/demo/csharp/demotest b/demo/csharp/demotest
--- a/demo/csharp/demotest
+++ b/demo/csharp/demotest
@@ -4,52 +4,34 @@ Fail()
     echo "FATAL(demo/csharp/demotest): $1"
     exit 1
 }
+
+TestDemo()
+{
+    echo "Testing demo: $1.cs"
+    exe/$* > test/$1.txt || Fail "Error testing $1.cs."
+    diff {correct,test}/$1.txt || Fail "Incorrect output from $1.cs."
+}
+
 rm -rf exe
 rm -f test/*.txt
-mkdir -p test
+mkdir -p test || exit 1
 dotnet build --output ${PWD}/exe || Fail "Error building ${PWD}/demo.sln"
 
-echo "Testing example: camera.cs"
-exe/camera 29 -81 2021-03-22T02:45:00Z > test/camera.txt || Fail "Error testing camera.cs."
-diff {correct,test}/camera.txt || Fail "Error comparing camera.cs output."
+TestDemo camera 29 -81 2021-03-22T02:45:00Z
+TestDemo moonphase 2019-06-15T09:15:32.987Z
+TestDemo positions +45.6 -90.7 2018-11-30T17:55:07.234Z
+TestDemo riseset 45 -90 2019-06-14T21:45:25Z
+TestDemo seasons 2020 > test/seasons.txt
+TestDemo culminate +30 -90 2015-02-28T00:00:00Z
+TestDemo horizon +25.5 -85.3 2016-12-25T12:30:45Z
+TestDemo lunar_eclipse 1988-01-01T00:00:00Z
+TestDemo triangulate 48.16042 24.49986 2019 18 7 48.27305 24.36401 662 83 12
 
-echo "Testing example: moonphase.cs"
-exe/moonphase 2019-06-15T09:15:32.987Z > test/moonphase.txt || Fail "Error testing moonphase.cs"
-diff {correct,test}/moonphase.txt || Fail "Error comparing moonphase.cs output."
-
-echo "Testing example: positions.cs"
-exe/positions +45.6 -90.7 2018-11-30T17:55:07.234Z > test/positions.txt || Fail "Error testing positions.cs"
-diff {correct,test}/positions.txt || Fail "Error comparing positions.cs output."
-
-echo "Testing example: riseset.cs"
-exe/riseset 45 -90 2019-06-14T21:45:25Z > test/riseset.txt || Fail "Error testing riseset.cs"
-diff {correct,test}/riseset.txt || Fail "Error comparing riseset.cs output."
-
-echo "Testing example: seasons.cs"
-exe/seasons 2020 > test/seasons.txt || Fail "Error testing seasons.cs"
-diff {correct,test}/seasons.txt || Fail "Error comparing seasons.cs output."
-
-echo "Testing example: culminate.cs"
-exe/culminate +30 -90 2015-02-28T00:00:00Z > test/culminate.txt || Fail "Error testing culminate.cs."
-diff {correct,test}/culminate.txt || Fail "Error comparing culminate.cs output."
-
-echo "Testing example: horizon.cs"
-exe/horizon +25.5 -85.3 2016-12-25T12:30:45Z > test/horizon.txt || Fail "Error testing horizon.cs"
-diff {correct,test}/horizon.txt || Fail "Error comparing horizon.cs output."
-
-echo "Testing example: lunar_eclipse.cs"
-exe/lunar_eclipse 1988-01-01T00:00:00Z > test/lunar_eclipse.txt || Fail "Error running lunar_eclipse.cs."
-diff {correct,test}/lunar_eclipse.txt || Fail "Error comparing lunar_eclipse.cs output."
-
-echo "Testing example: triangulate.cs"
-exe/triangulate 48.16042 24.49986 2019 18 7 48.27305 24.36401 662 83 12 > test/triangulate.txt || Fail "Error running triangulate.cs."
-diff {correct,test}/triangulate.txt || Fail "Error comparing triangulate.cs output."
-
-echo "Testing example: gravity.cs"
+echo "Testing demo: gravity.cs"
 for latitude in {0..90}; do
     exe/gravity ${latitude} 0 >> test/gravity.txt || Fail "Error running gravity.cs."
 done
 diff {correct,test}/gravity.txt || Fail "Error comparing gravity.cs output."
 
-echo "PASS: C# examples"
+echo "PASS: C# demos"
 exit 0
